--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26/07/2022 20:04:45
-- Server version: 10.4.17
-- Client version: 4.1
--

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

SET NAMES 'utf8';

USE oportobus_plataforma;

DROP TABLE IF EXISTS clientes;

DROP TABLE IF EXISTS escolas_criancas;

DROP TABLE IF EXISTS escolas_criancas_horarios;

DROP TABLE IF EXISTS localizacoes;

DROP TABLE IF EXISTS localizacoes_tipo;

DROP TABLE IF EXISTS servicos;

DROP TABLE IF EXISTS utilizadores;

DROP TABLE IF EXISTS utilizadores_alertas;

DROP TABLE IF EXISTS viaturas;

DROP TABLE IF EXISTS viaturas_abastecimentos;

DROP TABLE IF EXISTS viaturas_sessoes;

USE oportobus_plataforma;

CREATE TABLE viaturas_sessoes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  tipo ENUM('OUTRO','OFICINA','ABASTECIMENTO','SERVICO') NOT NULL,
  viatura_matricula VARCHAR(255) NOT NULL,
  funcionario_telemovel INT(11) NOT NULL,
  data_inicial DATETIME NOT NULL DEFAULT current_timestamp,
  data_final DATETIME DEFAULT NULL,
  kms_iniciais INT(11) NOT NULL,
  kms_finais INT(11) DEFAULT NULL,
  localizacao_inicial VARCHAR(255) DEFAULT NULL,
  localizacao_final VARCHAR(255) DEFAULT NULL,
  obs VARCHAR(255) DEFAULT NULL,
  ativa TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE viaturas_abastecimentos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  abastecimento_data DATETIME NOT NULL DEFAULT current_timestamp,
  abastecimento_localizacao VARCHAR(255) NOT NULL,
  viatura_matricula VARCHAR(255) NOT NULL,
  viatura_kms INT(11) NOT NULL,
  combustivel_tipo ENUM('DIESEL','GASOLINA','ELETRICO','GPL','ADBLUE') NOT NULL,
  combustivel_litros FLOAT NOT NULL,
  combustivel_valor FLOAT NOT NULL,
  responsavel_telemovel INT(11) NOT NULL,
  criador_telemovel INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE viaturas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  matricula VARCHAR(255) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  tipo ENUM('LIGEIRO') NOT NULL,
  pax INT(11) NOT NULL,
  cor VARCHAR(255) NOT NULL,
  cadeiras INT(11) NOT NULL,
  cartao TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE utilizadores_alertas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  data INT(11) NOT NULL,
  tipo INT(11) NOT NULL,
  link VARCHAR(255) NOT NULL,
  lido TINYINT(1) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  utilizador_telemovel INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 21,
AVG_ROW_LENGTH = 819,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE utilizadores (
  id INT(11) NOT NULL AUTO_INCREMENT,
  telemovel INT(9) NOT NULL,
  pin INT(4) DEFAULT NULL,
  nome_primeiro VARCHAR(255) NOT NULL,
  nome_ultimo VARCHAR(255) NOT NULL,
  morada VARCHAR(255) NOT NULL,
  nib INT(50) NOT NULL,
  nif INT(9) NOT NULL,
  mail VARCHAR(255) NOT NULL,
  cargo ENUM('OUTRO','VIGILANTE','MOTORISTA','MOTORISTAPESADOS','DONO','DESENVOLVEDOR') NOT NULL,
  ativo INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE servicos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  data_criacao DATETIME DEFAULT current_timestamp,
  data_servico_inicio DATETIME DEFAULT NULL,
  data_servico_fim DATETIME DEFAULT NULL,
  cliente_id INT(11) DEFAULT NULL,
  titulo VARCHAR(255) DEFAULT NULL,
  descricao VARCHAR(255) DEFAULT NULL,
  recorrente VARCHAR(1) DEFAULT 'N',
  estado ENUM('PRERESERVA','EFETIVO','CONCLUIDO') DEFAULT NULL,
  criador_telemovel INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE localizacoes_tipo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE localizacoes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  tipo TINYINT(4) DEFAULT NULL,
  morada VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE escolas_criancas_horarios (
  id INT(11) NOT NULL AUTO_INCREMENT,
  viatura_matricula VARCHAR(255) DEFAULT NULL,
  crianca_id INT(11) DEFAULT NULL,
  dia ENUM('SEGUNDA','TERCA','QUARTA','QUINTA','SEXTA','SABADO','DOMINGO','TODOSUTEIS','TODOS') DEFAULT NULL,
  recolha_hora TIME DEFAULT NULL,
  entrega_hora TIME DEFAULT NULL,
  recolha_localizacao_id INT(11) DEFAULT NULL,
  entrega_localizacao_id INT(11) DEFAULT NULL,
  obs VARCHAR(255) DEFAULT NULL,
  ativo TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE escolas_criancas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome_primeiro VARCHAR(255) DEFAULT NULL,
  nome_ultimo VARCHAR(255) DEFAULT NULL,
  escola_id INT(11) DEFAULT NULL,
  obs VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE clientes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  nif VARCHAR(255) DEFAULT NULL,
  iban VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;


INSERT INTO viaturas_sessoes VALUES
(2, 'SERVICO', 'EERRTT', 911999999, '2022-07-21 07:00:08', '2022-07-19 00:00:00', 1000, 1005, '{"latitude":"51.3998848","longitude":"-0.1671168"}', '{"latitude":"51.3998848","longitude":"-0.1671168"}', 'example service obs', 0),
(3, 'ABASTECIMENTO', 'EERRTT', 911999999, '2022-07-19 00:00:00', '2022-07-19 00:00:00', 12345, 12500, '{"latitude":"51.3998848","longitude":"-0.1671168"}', '{"latitude":"51.3998848","longitude":"-0.1671168"}', '', 0),
(4, 'SERVICO', 'QQVVPP', 911999999, '2022-07-23 22:36:15', '2022-07-23 22:39:25', 666666, 777777, '{"latitude":"51.3998848","longitude":"-0.1671168"}', '{"latitude":"51.3998848","longitude":"-0.1671168"}', '', 0),
(5, 'SERVICO', 'AABBCC', 911999999, '2022-07-23 22:39:40', '2022-07-23 22:40:00', 123457777, 123457784, '{"latitude":"51.3998848","longitude":"-0.1671168"}', '{"latitude":"51.3998848","longitude":"-0.1671168"}', '', 0),
(6, 'OFICINA', 'EERRTT', 911999999, '2022-07-23 22:40:09', '2022-07-23 22:40:16', 232323, 5635654, '{"latitude":"51.3998848","longitude":"-0.1671168"}', '{"latitude":"51.3998848","longitude":"-0.1671168"}', '', 0);


INSERT INTO viaturas_abastecimentos VALUES
(6, '2022-07-24 13:26:12', 'Random', 'AABBCC', 1000, 'DIESEL', 10, 2.2, 911999999, 911999999),
(7, '2022-07-24 13:27:22', 'Random', 'AABBCC', 1100, 'DIESEL', 10, 2.2, 911999999, 911999999),
(8, '2022-07-24 13:38:15', 'Random', 'EERRTT', 456464, 'GASOLINA', 20.5, 3.1, 911999999, 911999999),
(9, '2022-07-24 13:39:01', 'Random', 'EERRTT', 456464, 'GPL', 44, 0.75, 911999999, 911999999),
(10, '2022-07-24 13:41:40', 'Random', 'EERRTT', 456500, 'GPL', 3, 0.75, 911999999, 911999999),
(11, '2022-07-24 13:53:18', 'Random', 'EERRTT', 456630, 'GASOLINA', 17.4, 1.9, 911999999, 911999999);


INSERT INTO viaturas VALUES
(1, 'AABBCC', 'Brand Model', 'LIGEIRO', 5, 'black', 0, 0),
(2, 'EERRTT', 'Brand Model', 'LIGEIRO', 7, 'white', 0, 0),
(3, 'QQVVPP', 'Brand Model', 'LIGEIRO', 9, 'pink', 0, 0);


INSERT INTO utilizadores_alertas VALUES
(1, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488244),
(2, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488076),
(3, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488244),
(4, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488076),
(5, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488244),
(6, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488076),
(7, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488244),
(8, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488076),
(9, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488244),
(10, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488076),
(11, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488244),
(12, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura AABBCC', 930488076),
(13, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura EERRTT', 930488244),
(14, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura EERRTT', 930488076),
(15, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura QQVVPP', 930488244),
(16, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura QQVVPP', 930488076),
(17, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura QQVVPP', 930488244),
(18, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura QQVVPP', 930488076),
(19, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura EERRTT', 930488244),
(20, 0, 0, '#', 0, 'First Last acabou de abastecer a viatura EERRTT', 930488076);


INSERT INTO utilizadores VALUES
(1, 911999999, NULL, 'Flávio', 'Pereira', 'address', 454564654, 99999999, 'email', 'DESENVOLVEDOR', 1),
(2, 911888888, NULL, 'Joel', 'Ramalho', 'address', 1234567890, 1234567890, 'mail@mail.com', 'MOTORISTA', 1),
(3, 911777777, NULL, 'Jorge', 'Antunes', 'address', 1234567890, 1234567890, 'mail@mail.com', 'MOTORISTA', 1),
(4, 911666666, NULL, 'Marco', 'Patinha', 'address', 1234567890, 1234567890, 'mail@mail.com', 'DONO', 1);


INSERT INTO servicos VALUES
(1, '2022-07-25 18:53:17', '2022-07-25 19:52:18', '2022-07-25 19:52:18', 1, 'Example Service Title 1', 'Example Description', 'N', 'PRERESERVA', 0),
(2, '2022-07-26 18:23:31', '2022-07-26 19:22:40', '2022-07-31 19:22:40', 2, 'Example Title for Service 2', 'Example Description', 'N', 'EFETIVO', 0),
(3, '2022-07-26 18:24:18', '2022-07-26 19:23:54', '2022-07-30 19:23:54', 3, 'Example Title for Service 3', 'Example Description', 'N', 'CONCLUIDO', 0),
(4, '2022-07-26 18:25:18', '2022-07-26 19:24:54', '2022-08-26 19:24:54', 2, 'Example Service Title for Customer 2', 'Example Description', 'S', 'EFETIVO', 0),
(5, '2022-07-26 18:26:00', '2022-07-26 19:25:40', '2022-09-26 19:25:40', 1, 'Example Service Title for Customer 1', 'Example Description', 'N', 'PRERESERVA', 0);


INSERT INTO localizacoes_tipo VALUES
(1, 'Escola');


INSERT INTO localizacoes VALUES
(1, 'Escola X', 1, 'rua X'),
(2, 'Escola Y', 1, 'rua Y'),
(3, 'Escola Z', 1, 'rua Z'),
(4, 'Morada Criança X', 2, 'Rua XYZ');


INSERT INTO escolas_criancas_horarios VALUES
(1, NULL, 2, 'QUINTA', '08:00:00', '09:00:00', 4, 1, '', 1),
(2, 'AABBCC', 3, 'QUARTA', '08:00:00', '09:00:00', 1, 2, '', 0),
(3, NULL, 2, 'SEGUNDA', '08:00:00', '09:00:00', 4, 1, '', 1),
(4, NULL, 2, 'TERCA', '08:00:00', '09:00:00', 4, 1, '', 1),
(5, NULL, 2, 'SEXTA', '08:00:00', '09:00:00', 4, 1, '', 1),
(6, 'AABBCC', 2, 'QUARTA', '08:00:00', '09:00:00', 4, 1, 'Example Observation', 1);


INSERT INTO escolas_criancas VALUES
(1, 'José', 'Lima', 1, ''),
(2, 'Ana', 'Pereira', 2, ''),
(3, 'Alberto', 'Cardoso', 3, ''),
(4, 'Rafael', 'Semedo', 2, '');


INSERT INTO clientes VALUES
(1, 'Customer 1', 'mail@mail.com', '999999999', '999999'),
(2, 'Customer 2', 'mail@mail.com', '999999999', '999999'),
(3, 'Customer 3', 'mail@mail.com', '999999999', '999999');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;