--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 23/07/2022 23:29:12
-- Server version: 10.4.17
-- Client version: 4.1
--

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

SET NAMES 'utf8';

USE oportobus_plataforma;

DROP TABLE IF EXISTS clientes;

DROP TABLE IF EXISTS utilizadores;

DROP TABLE IF EXISTS utilizadores_alertas;

DROP TABLE IF EXISTS viaturas;

DROP TABLE IF EXISTS viaturas_abastecimentos;

DROP TABLE IF EXISTS viaturas_sessoes;

USE oportobus_plataforma;

CREATE TABLE viaturas_sessoes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  tipo ENUM('OUTRO','OFICINA','ABASTECIMENTO','SERVICO') NOT NULL,
  viatura_matricula VARCHAR(255) NOT NULL,
  funcionario_telemovel INT(11) NOT NULL,
  data_inicial DATETIME NOT NULL DEFAULT current_timestamp,
  data_final DATETIME DEFAULT NULL,
  kms_iniciais INT(11) NOT NULL,
  kms_finais INT(11) DEFAULT NULL,
  localizacao_inicial VARCHAR(255) DEFAULT NULL,
  localizacao_final VARCHAR(255) DEFAULT NULL,
  obs VARCHAR(255) DEFAULT NULL,
  ativa TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE viaturas_abastecimentos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  abastecimento_data DATE NOT NULL DEFAULT current_timestamp,
  abastecimento_localizacao VARCHAR(255) NOT NULL,
  viatura_matricula VARCHAR(255) NOT NULL,
  viatura_kms INT(11) NOT NULL,
  combustivel_tipo INT(11) NOT NULL,
  combustivel_litros INT(11) NOT NULL,
  combustivel_valor INT(11) NOT NULL,
  responsavel_telemovel INT(11) NOT NULL,
  criador_telemovel INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE viaturas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  matricula VARCHAR(255) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  tipo ENUM('LIGEIRO') NOT NULL,
  pax INT(11) NOT NULL,
  cor VARCHAR(255) NOT NULL,
  cadeiras INT(11) NOT NULL,
  cartao TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE utilizadores_alertas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  data INT(11) NOT NULL,
  tipo INT(11) NOT NULL,
  link VARCHAR(255) NOT NULL,
  lido TINYINT(1) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  utilizador_telemovel INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE utilizadores (
  id INT(11) NOT NULL AUTO_INCREMENT,
  telemovel INT(9) NOT NULL,
  pin INT(4) DEFAULT NULL,
  nome_primeiro VARCHAR(255) NOT NULL,
  nome_ultimo VARCHAR(255) NOT NULL,
  morada VARCHAR(255) NOT NULL,
  nib INT(50) NOT NULL,
  nif INT(9) NOT NULL,
  mail VARCHAR(255) NOT NULL,
  cargo ENUM('OUTRO','VIGILANTE','MOTORISTA','MOTORISTAPESADOS','DONO','DESENVOLVEDOR') NOT NULL,
  ativo INT(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

CREATE TABLE clientes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  nif VARCHAR(255) DEFAULT NULL,
  iban VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;


INSERT INTO viaturas_sessoes VALUES
(2, 'SERVICO', 'EERRTT', 911999999, '2022-07-21 07:00:08', '2022-07-19 00:00:00', 1000, 1005, '{"latitude":"51.3998848","longitude":"-0.1671168"}', '{"latitude":"51.3998848","longitude":"-0.1671168"}', 'example service obs', 0),
(3, 'ABASTECIMENTO', 'EERRTT', 911999999, '2022-07-19 00:00:00', '2022-07-19 00:00:00', 12345, 12500, '{"latitude":"51.3998848","longitude":"-0.1671168"}', '{"latitude":"51.3998848","longitude":"-0.1671168"}', '', 0);


-- Table oportobus_plataforma.viaturas_abastecimentos does not contain any data (it is empty)


INSERT INTO viaturas VALUES
(1, 'AABBCC', 'Brand Model', 'LIGEIRO', 5, 'black', 0, 0),
(2, 'EERRTT', 'Brand Model', 'LIGEIRO', 7, 'white', 0, 0),
(3, 'QQVVPP', 'Brand Model', 'LIGEIRO', 9, 'pink', 0, 0);


-- Table oportobus_plataforma.utilizadores_alertas does not contain any data (it is empty)


INSERT INTO utilizadores VALUES
(1, 911999999, NULL, 'Flavio', 'Pereira', 'address', 454564654, 99999999, 'email', 'DESENVOLVEDOR', 1);


INSERT INTO clientes VALUES
(1, 'Customer 1', 'mail@mail.com', '999999999', '999999'),
(2, 'Customer 2', 'mail@mail.com', '999999999', '999999'),
(3, 'Customer 3', 'mail@mail.com', '999999999', '999999');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;